name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14

      - run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
