name: Dev
on:
  push:
    branches:
      - master
      - dev-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16

      - run: yarn

      - name: Build
        # Disable CI flag so linter warnings aren't treaded as errors
        run: CI=false yarn build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.DEV_BUCKET }}
          bucket-region: ${{ secrets.S3_DEV_BUCKET_REGION }}
          invalidation: /*
          dist-id: ${{ secrets.CLOUDFRONT_ID_DEV }}
          delete-removed: false
          no-cache: true
          private: true
